export const GETSEARCHMOVIES = {
    GET_MOVIES: 'GET_MOVIES',
    GET_MOVIES_SUCCESS : 'GET_MOVIES_FULFILLED',
    GET_MOVIES_PENDING : 'GET_MOVIES_PENDING',
    GET_MOVIES_ERROR : 'GET_MOVIES_ERROR'
}

export const HANDLECHANGE = {
    HANDLE_NAME: 'HANDLE_NAME',
    HANDLE_TYPE: 'HANDLE_TYPE',
    HANDLE_YEAR: 'HANDLE_YEAR'
}
